name: Automatic Label Sync

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  label_sync:
    name: Automatic Label Synchronization
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          repository: 'RealShadowNova/.github'
      - name: Run Label Sync
        uses: crazy-max/ghaction-github-labeler@24d110aa46a59976b8a7f35518cb7f14f434c916 # v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          yaml-file: .github/labels.yml
